In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1. Loading the Iris dataset
iris = load_iris()
X, y = iris.data, iris.target

# 2. Splitting the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

# 3. Training the KNN Classifier
# n_neighbors=5 is the standard starting point for K
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

# 4. Making Predictions
y_pred = classifier.predict(X_test)

# 5. Formatted Output for Lab Record
print("Output:")
print(f"\nPredicted Values: {y_pred}")
print(f"\nActual Values: {y_test}")

accuracy = accuracy_score(y_test, y_pred)
print(f"\nAccuracy : {accuracy:.7f}")

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nResult: KNN Classification Complete!")

Output:

Predicted Values: [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]

Actual Values: [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]

Accuracy : 1.0000000

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

Result: KNN Classification Complete!
